# Job execution time - Each job in a workflow can run for up to 6 hours of execution time.
# Workflow run time - Each workflow run is limited to 35 days

name: windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: msys2 {0}

# each job runs under a NEW image
jobs:
  should_run:
    runs-on: ubuntu-latest
    name: should_i_run
    outputs:
      output1: ${{ steps.check.outputs.target_commit_id }}
    steps:
     - name: check
       run: |
         wget https://gist.github.com/mgood7123/47957c59a4b0cbda11875632ee0b8f15/raw/7e876a60f2735cf7e60150a9a29edf6ddaad20a8/check.cpp -O check.cpp
         cat << EOF > data.json
         ${{toJSON(github.event.commits.*)}}
         EOF
         cat -n data.json
         git clone https://github.com/danielaparker/jsoncons --depth=1
         g++ --std=c++17 -I jsoncons/include check.cpp -o check
         ./check 2 >> "$GITHUB_OUTPUT" # check for android [1] windows [2] linux [3] windows [4]
       shell: bash
  
  build_deps:
    needs: should_run
    # so we can upload releases
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            sys: clang64

    runs-on: ${{ matrix.os }}

    name: deps - ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{needs.should_run.outputs.output1}}
          submodules: recursive

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          path-type: strict

      - name: test symlink support
        run: |
          export MSYS=winsymlinks:native
          touch a
          ln -s a b
          cp -v -r deps/zstd/tests/cli-tests/bin .
          rm -f a
          rm -f b
          rm -rf bin

      - name: update packages
        run: |
          pacman -Sy

      - name: install pacboy
        run: |
          pacman -Syu --noconfirm --needed pactoys

      - name: update packages
        run: |
          pacboy -Sy

      - name: install procps
        run: |
          pacboy -S --noconfirm --needed procps

      - name: install git
        run: |
          pacboy -S --noconfirm --needed git

      - name: install findutils
        run: |
          pacboy -S --noconfirm --needed findutils
          which find
          ls -l /usr/bin/find.exe

      - name: install clang 17
        run: |
          pacboy -S --noconfirm --needed clang:p

      - name: install cmake
        run: |
          pacboy -S --noconfirm --needed make:p cmake:p

      - name: install autotools
        run: |
          pacboy -S --noconfirm --needed autotools:p

      - name: install patch
        run: |
          pacboy -S --noconfirm --needed patch

      - name: install gperf
        run: |
          pacboy -S --noconfirm --needed gperf:p

      - name: install groff
        run: |
          pacboy -S --noconfirm --needed groff

      - name: install gettext
        run: |
          pacboy -S --noconfirm --needed gettext

      - name: clone libiconv
        run: |
          export MSYS=winsymlinks:native
          cd deps ; git clone git://git.savannah.gnu.org/libiconv.git libiconv --recursive --depth=1

      - name: libiconv autopull.sh
        run: |
          export MSYS=winsymlinks:native
          cd deps ; cd libiconv ; ./autopull.sh --one-time

      - name: check if split program is cached
        run: |
          export MSYS=winsymlinks:native
          cd split
          chmod +x ../try_get_release.sh
          ../try_get_release.sh   mgood7123   llvm-project-prebuilts   storage--split--windows   split_build.tar || true

      - name: build split program
        run: |
          export MSYS=winsymlinks:native
          chmod +x try_get_release.sh
          cd split
          D:/a/_temp/msys64/msys2_shell.cmd -defterm -here -no-start -msys2 -shell bash -c "pacman -S --noconfirm --needed cmake make gcc ; cd split ; chmod +x make.sh ; ./make.sh"

      - name: archive split build directory
        run: |
          export MSYS=winsymlinks:native
          cd split
          # we need only the rootfs in the next stage
          cp /usr/bin/msys-2.0.dll BUILD_DEBUG/BUILD_ROOT/ROOTFS/bin
          mv BUILD_DEBUG/BUILD_ROOT/ROOTFS .
          tar -cf split_build.tar BUILD_DEBUG
          sha512sum split_build.tar > split_build.tar.sha512
          rm -rf BUILD_DEBUG
          # preserve the directory structure
          mkdir BUILD_DEBUG
          mkdir BUILD_DEBUG/BUILD_ROOT
          mv ROOTFS BUILD_DEBUG/BUILD_ROOT
          tar -cf split_rootfs.tar BUILD_DEBUG
          sha512sum split_rootfs.tar > split_rootfs.tar.sha512
          cd ..
          mkdir split_exe
          cp split/BUILD_DEBUG/BUILD_ROOT/ROOTFS/bin/split.exe split_exe
          cp /usr/bin/msys-2.0.dll split_exe
          tar -cf split.exe.tar split_exe
          sha512sum split.exe.tar > split.exe.tar.sha512
          rm -rf split/BUILD_DEBUG
          rm -rf split_exe
          tar -xf split.exe.tar
          /bin/ls -l /usr/bin/msys-2.0.dll
          /bin/ls -l split_exe

      - name: list files
        run: |
          ls -l
      
      - name: upload split build directory
        if: success() # if we cancel during the upload, wait for it to complete
        uses: "ncipollo/release-action@v1"
        with:
          name: "split"
          tag: "storage--split--windows"
          makeLatest: true
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: |
            ./split/split_build.tar
            ./split/split_build.tar.sha512
            ./split/split_rootfs.tar
            ./split/split_rootfs.tar.sha512
            ./split.exe.tar
            ./split.exe.tar.sha512

      - name: check if build directory is cached
        run: |
          export MSYS=winsymlinks:native

          URL=https://github.com/mgood7123/llvm-project-prebuilts/releases/download/storage--deps--windows--debug/build.split.map
          ./split_exe/split.exe --join $URL --out BUILD_DEBUG || true

      - name: cmake build deps - Debug
        run: |
          export MSYS=winsymlinks:native
          export ACLOCAL_PATH=D:/a/_temp/msys64/usr/share/aclocal
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-g3 -O0" -DCMAKE_CXX_FLAGS="-g3 -O0" -DCMAKE_MAKE_PROGRAM=mingw32-make -DCMAKE_COLOR_DIAGNOSTICS=ON -DCMAKE_COLOR_MAKEFILE=ON -S . -B BUILD_DEBUG

      - name: archive build directory
        run: |
          export MSYS=winsymlinks:native

          # 256 mb
          #
          ./split_exe/split.exe --split -r BUILD_DEBUG/BUILD_ROOT/ROOTFS --name rootfs --size 256000000
          # 256 mb
          #
          ./split_exe/split.exe --split -r BUILD_DEBUG --name build --size 256000000

      - name: list files
        run: |
          ls -l
      
      - name: upload build directory
        if: success() # if we cancel during the upload, wait for it to complete
        uses: "ncipollo/release-action@v1"
        with:
          name: "llvm 18 deps - windows - DEBUG"
          tag: "storage--deps--windows--debug"
          makeLatest: true
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: |
            ./build.split.*
            ./rootfs.split.*






  build_llvm_stage_1:
    needs: build_deps
    # so we can upload releases
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            sys: clang64

    runs-on: ${{ matrix.os }}

    name: llvm stage 1 - ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{needs.should_run.outputs.output1}}
          # we dont need submodules anymore

      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          path-type: strict

      - name: test symlink support
        run: |
          export MSYS=winsymlinks:native
          touch a
          ln -s a b
          cp -v -r deps/zstd/tests/cli-tests/bin .
          rm -f a
          rm -f b
          rm -rf bin

      - name: update packages
        run: |
          pacman -Sy

      - name: install pacboy
        run: |
          pacman -Syu --noconfirm --needed pactoys

      - name: update packages
        run: |
          pacboy -Sy

      - name: install findutils
        run: |
          pacboy -S --noconfirm --needed findutils
          which find
          ls -l /usr/bin/find.exe

      - name: install clang 17
        run: |
          pacboy -S --noconfirm --needed clang:p

      - name: install cmake
        run: |
          pacboy -S --noconfirm --needed make:p cmake:p

      - name: install git
        run: |
          pacboy -S --noconfirm --needed git

      - name: check if split program is cached
        run: |
          export MSYS=winsymlinks:native
          cd split
          chmod +x ../try_get_release.sh
          ../try_get_release.sh   mgood7123   llvm-project-prebuilts   storage--split--windows   split.exe.tar

      - name: check if build directory is cached
        run: |
          export MSYS=winsymlinks:native

          URL1=https://github.com/mgood7123/llvm-project-prebuilts/releases/download/storage--llvm-stage-1--windows--debug/build.split.map
          URL2=https://github.com/mgood7123/llvm-project-prebuilts/releases/download/storage--deps--windows--debug/rootfs.split.map

          if ./split_exe/split.exe --join $URL1 --out BUILD_DEBUG
            then
              true;
            else
              mkdir BUILD_DEBUG/BUILD_ROOT
              ./split_exe/split.exe --join $URL2 --out BUILD_DEBUG/BUILD_ROOT/ROOTFS
          fi

      - name: clone llvm-project
        run: |
          git clone --depth=1 --recursive https://github.com/llvm/llvm-project

      - name: cmake LLVM STAGE 1 - Debug - Configure
        run: |
          export MSYS=winsymlinks:native
          export ACLOCAL_PATH=D:/a/_temp/msys64/usr/share/aclocal
          cmake -G "Unix Makefiles" -DLLVM_OPTIMIZED_TABLEGEN=true -DCMAKE_MODULE_PATH="$(pwd)/cmake/packages" -DCMAKE_INSTALL_PREFIX="$(pwd)/BUILD_DEBUG/BUILD_ROOT/ROOTFS" -DLLVM_BUILD_ROOT__ROOTFS="$(pwd)/BUILD_DEBUG/BUILD_ROOT/ROOTFS" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-g3 -O0" -DCMAKE_CXX_FLAGS="-g3 -O0" -DCMAKE_MAKE_PROGRAM=mingw32-make -DCMAKE_COLOR_DIAGNOSTICS=ON -DCMAKE_COLOR_MAKEFILE=ON -S llvm-project/llvm -B BUILD_DEBUG

      - name: cmake LLVM STAGE 1 - Debug - Build
        run: |
          export MSYS=winsymlinks:native
          cmake --build BUILD_DEBUG

      - name: cmake LLVM STAGE 1 - Debug - Install
        run: |
          export MSYS=winsymlinks:native
          cmake --install BUILD_DEBUG

      - name: archive build directory
        run: |
          export MSYS=winsymlinks:native

          # 256 mb
          #
          ./split_exe/split.exe --split -r BUILD_DEBUG/BUILD_ROOT/ROOTFS --name rootfs --size 256000000
          # 256 mb
          #
          ./split_exe/split.exe --split -r BUILD_DEBUG --name build --size 256000000

      - name: list files
        run: |
          ls -l
      
      - name: upload build directory
        if: success() # if we cancel during the upload, wait for it to complete
        uses: "ncipollo/release-action@v1"
        with:
          name: "llvm 18 stage 1 - windows - DEBUG"
          tag: "storage--llvm-stage-1--windows--debug"
          makeLatest: true
          generateReleaseNotes: false
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: |
            ./build.split.*
            ./rootfs.split.*
